const fs = require('fs');
const path = require('path');

const trackName = process.argv[2];
if (!trackName) {
  console.error("❌ Error: Please provide a track name (e.g., 'Python Data Science').");
  process.exit(1);
}

const slug = trackName.toLowerCase().replace(/\s+/g, '-');
// Find the next phase number (e.g., Phase 07)
const tutorialsDir = path.join(__dirname, '..', '..', '..', 'tutorials');
const existingPhases = fs.readdirSync(tutorialsDir).filter(f => f.match(/^\d{2}-/)).length;
const phaseNum = (existingPhases + 1).toString().padStart(2, '0');
const trackDir = path.join(tutorialsDir, `${phaseNum}-${slug}`);

if (!fs.existsSync(trackDir)) {
  fs.mkdirSync(trackDir, { recursive: true });
  console.log(`📁 Created track directory: ${trackDir}`);
}

const readmeContent = `# Phase ${phaseNum}: ${trackName} Domain Track\n\nWelcome to the ${trackName} track. This track was autonomously generated by the Meta-Registry Architect.\n\n## 🛤️ Tasks\n- [ ] Task 21: Initial Setup\n- [ ] Task 22: Advanced Concepts\n- [ ] Task 23: Production Implementation\n\n---`;
fs.writeFileSync(path.join(trackDir, 'README.md'), readmeContent);

console.log(`✅ Scaffolding complete for ${trackName}. Initial README.md created at ${trackDir}/README.md.`);
